services:
- docker
before_script:
- echo "$DOCKER_PASSWORD" | docker login -u atsubot --password-stdin
- export ATSU_VERSION=$(docker run -v $(pwd):/src -e BUILD_ENV="$(env | grep 'USER\|TRAVIS\|ATSU\|GITHUB')" ghcr.io/atsu/centosgobuilder:latest sqrl info -v version)
- echo "${ATSU_VERSION}"
script:
- make build
- git status
notifications:
  slack:
    rooms:
      secure: g1CJ58ea+IAWszK7ahfvBvXD94F7yJyUZyKO/PiFPGcS4u7HV9wOUkayVLhzcNozznGpu6oZaCweyB/BVm8WJaBC2TptKb91LNNGey5+5vfmvmzAYPsPWjVQCidJeXYI+P5EG9aRQBYXm56DkM5bj4Ts1nKva6ZqTRf5VtGYHIhDDV54ybpJChUr2Jes2WU90p5BhkOqx7tVZjwzjmM4lulxcdlzW7Wa7Ya1Z02bJe5lMeIwp2afOEkvbDo+hfJO/y5ygPJWvHyjzm/RUKcwxlGTHyuS2MYJLC02fDrm8yQXHgWgAdfXgTNV8njDDvwivQpiG1j/aJ4XIVOZLmHcdEY/GXXODmu4/kaqxdSyZMpl02iPScZ8ntgIKsVAMfq42nalxoS16d2yIH5fSy0kcAvSduuK4LKYeTixt1KL640vPkxXbLYE/5vARHHPjcQioarXilZBdWjiDFCign22/zlMS2oVWGFY1n33i0xVfYYofCSsRJzOQBf1m3nZkOt83BFyesJSQjaoMM3pvhbBz+MFg2YdUuZBz/2hOgY0h03G5mxG0DGEItuhOfYaDO3aFtN1GwnZI3mWkSCv2BTqDXmqs51gjJq0VI7NbOudjQGrSY6EdbH7o3efxTMrvxSO2uKulkkTd1eOQvpJLjmfeNqPDbIe3YdvATh+1M90uh4=
before_deploy:
- make tag
deploy:
  provider: releases
  name: ${ATSU_VERSION}
  api_key:
    secure: Q2OnlK2zG/KoKjDoxtia0nSRFEs8Clt5I/MiEaCaf/XWoqPsuAUyINjPSgE5g3ptw6Ni9lNAX1KX0jZ4My2dZ9Tsz0U22JxQFr1gSXBD2ZAMPjgQSZ2ds5tBasNvRJrnXm/vifet3IcxYp50GUUSaThi+fcf7LqC3+DGAvflbIY0k26RoubGwtgKlID2FZfqr7r+yvfnB7GCDiHdSvLgnyaX7GfJsl8x+xniFVVZlDy1HJ6F4TpO96wlupK3BJ95XxCjYnjRbK2RFVMHi7yhPh8fIxaVK1VtWvz6bcS4Ge03WEJWV2gycz3cxG9VaW+U2GWtZHsSPjrfoZcClb3MOsOqSRxiqghkDz187+mz1OSOaOkKWIWBo/kC8L9UKEMXTUZYqnD6Qw5fq6Ul3Gx7ll+9CBsvY6cF/8si8+VMeqJtMhML13XX0aBfgVTIkwfszlBX1rd04PuY+dLMD4S6dm1yEeLyhUdi3879Gqn4C2YBxPGoAwBCwTBH/WjAjMyYU9H6iFPLa0eZ/fy7YTm4UDNUAVDTmYyPQbjNjgcueQknybhoYHivbH8UZ2hdIQbiCuW2PHcGEpP39p5OaRWjZR7d4vtRW12IHwtfcDuT7Sv75WVaPW2CclPc3WToGNurrG8n/ilIMucXcTJwWqgzxpG4Bita+2nP3hYv1WJDUng=
  on:
    condition: $ATSU_RELEASE = true
